{% set name = "pycep-parser" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycep_parser-{{ version }}.tar.gz
  sha256: f9d6d7dd7487cfa35cdbc0d8002596cbee50d46c3cb1a849040fd1346941c7b1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.7.0,<4.0.0
    - lark >=1.1.2
    - regex >=2022.1.18
    - typing-extensions >=3.10.0
    - importlib-resources >=2.0.0

test:
  imports:
    - pycep
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gruebel/pycep
  summary: A Python based Bicep parser
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - borchero
    - nick-harmening
